version: '3.8'

services:
  web:
    build: .
    container_name: django-blog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE=mydatabase:
      MYSQL_USER=myuser:
      MYSQL_PASSWORD=mypassword:
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
