apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: yolo
spec:
  type: NodePort  # Cambiar de ClusterIP a NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306        # Puerto del servicio
      targetPort: 3306  # Puerto del contenedor
      nodePort: 30036   # Puerto expuesto en el nodo
